### ISSUE TITLE
Request - HD Skins Support

### ISSUE THREAD

**Issue by X00LA** [samolego/FabricTailor#12]
Hi,

is there any chance you could add HD-Skin support of any kind.
It would be nice when a player could add a custom link which loads a custom hd skin.

Thanks and Regards

**Comment by samolego** [comment]
Hi, thanks for the suggestion, but this is kinda out of scope for FabricTailor atm, since it's similar to #3 ...

One of the core ideas for the mod is that it can work server-side only, where it's not possible to implement this.

With the latest addition of client screen to change skin however, I could do a client-only HD skin support, so it would be limited to singleplayer.
This will probably not be the priority, but might be implemented in the future.

**Comment by X00LA** [comment]
Hi, thank you for the reply.
The HD-Skin feature would be nice but I understand your point.
I hope, that some time in the future Minecraft will support HD-Skins out of the box. This would be great. So we could have HD resource packs with the matching skins.
Ah, dreams are a wonderful thing.... ;D

Regards

**Comment by samolego** [comment]
(Finally) implemented in 2.0.0
